function GetNavXMLports {
    $XMLports = 
        ('XMLport 1;','XMLport "Consolidation Import/Export";'),
        ('XMLport 10;','XMLport "IC G/L Account Import/Export";'),
        ('XMLport 11;','XMLport "IC Dimension Import/Export";'),
        ('XMLport 12;','XMLport "IC Outbox Imp/Exp";'),
        ('XMLport 1000;','XMLport "SEPA CT pain.001.001.03";'),
        ('XMLport 1010;','XMLport "SEPA DD pain.008.001.02";'),
        ('XMLport 1220;','XMLport "Data Exch. Import - CSV";'),
        ('XMLport 1225;','XMLport "Imp / Exp Data Exch Def & Map";'),
        ('XMLport 1230;','XMLport "Export Generic CSV";'),
        ('XMLport 1231;','XMLport "Export Generic Fixed Width";'),
        ('XMLport 1232;','XMLport "Exp. Bank Data Conv. Serv.-CT";'),
        ('XMLport 1501;','XMLport "Import / Export Workflow";'),
        ('XMLport 1600;','XMLport "Sales Invoice - PEPPOL 2.1";'),
        ('XMLport 1601;','XMLport "Sales Credit Memo - PEPPOL 2.1";'),
        ('XMLport 1602;','XMLport "Sales Invoice - PEPPOL 2.0";'),
        ('XMLport 1603;','XMLport "Sales Credit Memo - PEPPOL 2.0";'),
        ('XMLport 1660;','XMLport "Import Payroll";'),
        ('XMLport 5050;','XMLport "Export Contact";'),
        ('XMLport 5051;','XMLport "Export Segment Contact";'),
        ('XMLport 5151;','XMLport "Integration Records";'),
        ('XMLport 5900;','XMLport "Imp. IRIS to Area/Symptom Code";'),
        ('XMLport 5901;','XMLport "Import IRIS to Fault Codes";'),
        ('XMLport 5902;','XMLport "Import IRIS to Resol. Codes";'),
        ('XMLport 8610;','XMLport "Config. Data Schema";'),
        ('XMLport 8611;','XMLport "Config. Questionnaire Schema";'),
        ('XMLport 9000;','XMLport "Export/Import User Groups";'),
        ('XMLport 9010;','XMLport "Export/Import Plans";'),
        ('XMLport 9170;','XMLport "Profile Import/Export";'),
        ('XMLport 9171;','XMLport "Import/Export Permission Sets";'),
        ('XMLport 9172;','XMLport "Import/Export Permissions";'),
        ('XMLport 9990;','XMLport "Code Coverage Summary";'),
        ('XMLport 9991;','XMLport "Code Coverage Detailed";'),
        ('XMLport 10800;','XMLport "Export G/L Entries";'),
        ('XMLport 10863;','XMLport "Import/Export Parameters";'),
        ('XMLport 130400;','XMLport "CAL Test Suite";'),
        ('XMLport 130401;','XMLport "CAL Test Results";'),
        ('XMLport 130402;','XMLport "CAL Import Enabled Codeunit";'),
        ('XMLport 130403;','XMLport "CAL Export Test Result";'),
        ('XMLport 130406;','XMLport "CAL Test Coverage Map";'),
        ('XMLport 20003960;','XMLport "Export Purch.Orders to Webshop";'),
        ('XMLport 20003970;','XMLport "Purchase Prices Import";'),
        ('XMLport 20003973;','XMLport "Excel Document Import/Export";'),
        ('XMLport 20003974;','XMLport "Analysis View Import/Export";'),
        ('XMLport 20003975;','XMLport "Acc. Schedule Import/Export";'),
        ('XMLport 20003976;','XMLport "Column Layout Import/Export";'),
        ('XMLport 20004025;','XMLport "Promotion Import/Export";'),
        ('XMLport 20004029;','XMLport "Imp. Sales Ctr. Bonus Qualif.";'),
        ('XMLport 20004180;','XMLport "AccVer";'),
        ('XMLport 20004250;','XMLport "HASS Item Update";'),
        ('XMLport 20004251;','XMLport "Import Sales Items";'),
        ('XMLport 20004260;','XMLport "Sales Ctr. Price Import";'),
        ('XMLport 20004261;','XMLport "Supporting Turnover Import";'),
        ('XMLport 20004281;','XMLport "Report 2x Imp/Exp Item Data";'),
        ('XMLport 20004290;','XMLport "HASS Order Import";'),
        ('RunObject=XMLport 1','RunObject=XMLport "Consolidation Import/Export"'),
        ('RunObject=XMLport 10','RunObject=XMLport "IC G/L Account Import/Export"'),
        ('RunObject=XMLport 11','RunObject=XMLport "IC Dimension Import/Export"'),
        ('RunObject=XMLport 12','RunObject=XMLport "IC Outbox Imp/Exp"'),
        ('RunObject=XMLport 1000','RunObject=XMLport "SEPA CT pain.001.001.03"'),
        ('RunObject=XMLport 1010','RunObject=XMLport "SEPA DD pain.008.001.02"'),
        ('RunObject=XMLport 1220','RunObject=XMLport "Data Exch. Import - CSV"'),
        ('RunObject=XMLport 1225','RunObject=XMLport "Imp / Exp Data Exch Def & Map"'),
        ('RunObject=XMLport 1230','RunObject=XMLport "Export Generic CSV"'),
        ('RunObject=XMLport 1231','RunObject=XMLport "Export Generic Fixed Width"'),
        ('RunObject=XMLport 1232','RunObject=XMLport "Exp. Bank Data Conv. Serv.-CT"'),
        ('RunObject=XMLport 1501','RunObject=XMLport "Import / Export Workflow"'),
        ('RunObject=XMLport 1600','RunObject=XMLport "Sales Invoice - PEPPOL 2.1"'),
        ('RunObject=XMLport 1601','RunObject=XMLport "Sales Credit Memo - PEPPOL 2.1"'),
        ('RunObject=XMLport 1602','RunObject=XMLport "Sales Invoice - PEPPOL 2.0"'),
        ('RunObject=XMLport 1603','RunObject=XMLport "Sales Credit Memo - PEPPOL 2.0"'),
        ('RunObject=XMLport 1660','RunObject=XMLport "Import Payroll"'),
        ('RunObject=XMLport 5050','RunObject=XMLport "Export Contact"'),
        ('RunObject=XMLport 5051','RunObject=XMLport "Export Segment Contact"'),
        ('RunObject=XMLport 5151','RunObject=XMLport "Integration Records"'),
        ('RunObject=XMLport 5900','RunObject=XMLport "Imp. IRIS to Area/Symptom Code"'),
        ('RunObject=XMLport 5901','RunObject=XMLport "Import IRIS to Fault Codes"'),
        ('RunObject=XMLport 5902','RunObject=XMLport "Import IRIS to Resol. Codes"'),
        ('RunObject=XMLport 8610','RunObject=XMLport "Config. Data Schema"'),
        ('RunObject=XMLport 8611','RunObject=XMLport "Config. Questionnaire Schema"'),
        ('RunObject=XMLport 9000','RunObject=XMLport "Export/Import User Groups"'),
        ('RunObject=XMLport 9010','RunObject=XMLport "Export/Import Plans"'),
        ('RunObject=XMLport 9170','RunObject=XMLport "Profile Import/Export"'),
        ('RunObject=XMLport 9171','RunObject=XMLport "Import/Export Permission Sets"'),
        ('RunObject=XMLport 9172','RunObject=XMLport "Import/Export Permissions"'),
        ('RunObject=XMLport 9990','RunObject=XMLport "Code Coverage Summary"'),
        ('RunObject=XMLport 9991','RunObject=XMLport "Code Coverage Detailed"'),
        ('RunObject=XMLport 10800','RunObject=XMLport "Export G/L Entries"'),
        ('RunObject=XMLport 10863','RunObject=XMLport "Import/Export Parameters"'),
        ('RunObject=XMLport 130400','RunObject=XMLport "CAL Test Suite"'),
        ('RunObject=XMLport 130401','RunObject=XMLport "CAL Test Results"'),
        ('RunObject=XMLport 130402','RunObject=XMLport "CAL Import Enabled Codeunit"'),
        ('RunObject=XMLport 130403','RunObject=XMLport "CAL Export Test Result"'),
        ('RunObject=XMLport 130406','RunObject=XMLport "CAL Test Coverage Map"'),
        ('RunObject=XMLport 20003960','RunObject=XMLport "Export Purch.Orders to Webshop"'),
        ('RunObject=XMLport 20003970','RunObject=XMLport "Purchase Prices Import"'),
        ('RunObject=XMLport 20003973','RunObject=XMLport "Excel Document Import/Export"'),
        ('RunObject=XMLport 20003974','RunObject=XMLport "Analysis View Import/Export"'),
        ('RunObject=XMLport 20003975','RunObject=XMLport "Acc. Schedule Import/Export"'),
        ('RunObject=XMLport 20003976','RunObject=XMLport "Column Layout Import/Export"'),
        ('RunObject=XMLport 20004025','RunObject=XMLport "Promotion Import/Export"'),
        ('RunObject=XMLport 20004029','RunObject=XMLport "Imp. Sales Ctr. Bonus Qualif."'),
        ('RunObject=XMLport 20004180','RunObject=XMLport "AccVer"'),
        ('RunObject=XMLport 20004250','RunObject=XMLport "HASS Item Update"'),
        ('RunObject=XMLport 20004251','RunObject=XMLport "Import Sales Items"'),
        ('RunObject=XMLport 20004260','RunObject=XMLport "Sales Ctr. Price Import"'),
        ('RunObject=XMLport 20004261','RunObject=XMLport "Supporting Turnover Import"'),
        ('RunObject=XMLport 20004281','RunObject=XMLport "Report 2x Imp/Exp Item Data"'),
        ('RunObject=XMLport 20004290','RunObject=XMLport "HASS Order Import"')
}