function GetNavZSTables {
    $Tables = 
		('Record "Zepter Soft Setup"','Record "Zepter Soft Setup"'),
		('Record "Zepter Soft User"','Record "Zepter Soft User"'),
		('Record "Analysis Overview"','Record "ZS Analysis Overview"'),
		('Record Calendar;','Record "ZS Calendar";'),
		('Record "Calendar Base Unit"','Record "ZS Calendar Base Unit"'),
		('Record "Calendar Detail"','Record "ZS Calendar Detail"'),
		('Record "Commission Calculation Code"','Record "ZS Comm. Calculation Code"'),
		('Record "Calculation Register"','Record "ZS Comm. Calculation Register"'),
		('Record "Commission Calendar"','Record "ZS Comm. Calendar"'),
		('Record "Commission Entry Allocation"','Record "ZS Comm. Entry Allocation"'),
		('Record "Detailed Comm. Ledg. Entry"','Record "ZS Comm. Ledger Detailed Entry"'),
		('Record "Commission Ledger Entry"','Record "ZS Comm. Ledger Entry"'),
		('Record "Rep. Commission Par. Exception"','Record "ZS Comm. Par. Exception"'),
		('Record "Commission Param by Contract"','Record "ZS Comm. Param by Contract"'),
		('Record "Commission Param by Level"','Record "ZS Comm. Param by Level"'),
		('Record "Commission Param by Turnover"','Record "ZS Comm. Param by Turnover"'),
		('Record "Partner Commission Setup"','Record "ZS Comm. Partner Setup"'),
		('Record "Commission Payment Qualifier"','Record "ZS Comm. Payment Qualifier"'),
		('Record "Sales Ctr. Initial Commission"','Record "ZS Comm. Sales Ctr. Initial"'),
		('Record "Sales Ctr. Commission Rule"','Record "ZS Comm. Sales Ctr. Rule"'),
		('Record "Commission Setup"','Record "ZS Comm. Setup"'),
		('Record "Commission Worksheet"','Record "ZS Comm. Worksheet"'),
		('Record "Imp. Purchase Header"','Record "ZS Imp. Purchase Header"'),
		('Record "Imp. Purchase Line"','Record "ZS Imp. Purchase Line"'),
		('Record "Ledger Entry Comment Line"','Record "ZS Ledger Entry Comment Line"'),
		('Record "Personal Data Proc. Consent"','Record "ZS Personal Data Proc. Consent"'),
		('Record "Personal Data Processing Code"','Record "ZS Personal Data Proces. Code"'),
		('Record "Personal Data Protection Field"','Record "ZS Personal Data Protec. Field"'),
		('Record "Personal Data Request Entry"','Record "ZS Personal Data Req. Entry"'),
		('Record "Personal Data Request"','Record "ZS Personal Data Request"'),
		('Record "Personal Voucher Ledger Entry"','Record "ZS Personal Vouch. Ledg. Entry"'),
		('Record "Personal Voucher"','Record "ZS Personal Voucher"'),
		('Record "Voucher Price"','Record "ZS Personal Voucher Price"'),
		('Record "Personal Voucher Template"','Record "ZS Personal Voucher Template"'),
		('Record "Contract Journal Batch"','Record "ZS Pmt. Ctr. Journal Batch"'),
		('Record "Contract Journal Line"','Record "ZS Pmt. Ctr. Journal Line"'),
		('Record "Contract Journal Template"','Record "ZS Pmt. Ctr. Journal Template"'),
		('Record "Detailed Contract Ledger Entry"','Record "ZS Pmt. Ctr. Ledg. Det. Entry"'),
		('Record "Contract Ledger Entry"','Record "ZS Pmt. Ctr. Ledger Entry"'),
		('Record "ZS Contract Register"','Record "ZS Pmt. Ctr. Register"'),
		('Record "Filter Part Buffer"','Record "ZS Pmt. Filter Part Buffer"'),
		('Record "Det. Freezing Ledger Entry"','Record "ZS Pmt. Freez.Ledg. Det. Entry"'),
		('Record "Freezing Ledger Entry"','Record "ZS Pmt. Freez.Ledg. Entry"'),
		('Record "Pmt. Return Wksh. Batch"','Record "ZS Pmt. Return Wksh. Batch"'),
		('Record "Pmt. Return Wksh. Line"','Record "ZS Pmt. Return Wksh. Line"'),
		('Record "Pmt. Return Wksh. Template"','Record "ZS Pmt. Return Wksh. Template"'),
		('Record "Sales Adv. Corr. Header"','Record "ZS Pmt. Sales Adv.Corr. Header"'),
		('Record "Sales Adv. Corr. Line"','Record "ZS Pmt. Sales Adv.Corr. Line"'),
		('Record "Advance Application"','Record "ZS Pmt. Sales Advance Appl."'),
		('Record "Sales Advance Header"','Record "ZS Pmt. Sales Advance Header"'),
		('Record "Sales Advance Line"','Record "ZS Pmt. Sales Advance Line"'),
		('Record "Transfer Order"','Record "ZS Pmt. Transfer Order"'),
		('Record "Transfer Order Setup"','Record "ZS Pmt. Transfer Order Setup"'),
		('Record "Rank & Turnover Addit. Setup"','Record "ZS Rank & Turn. Addit. Setup"'),
		('Record "Rank & Turnover Definition"','Record "ZS Rank & Turnover Definition"'),
		('Record "Rank & Turnover Setup"','Record "ZS Rank & Turnover Setup"'),
		('Record "Representative Active"','Record "ZS Rep. Active"'),
		('Record "Representative Active Entry"','Record "ZS Rep. Active Entry"'),
		('Record "Detailed Repr. Turn. Entry"','Record "ZS Rep. Detailed Turn. Entry"'),
		('Record "Detailed Repr. Turnover"','Record "ZS Rep. Detailed Turnover"'),
		('Record "Representative Rank"','Record "ZS Rep. Rank"'),
		('Record "Representative Rank Entry"','Record "ZS Rep. Rank Entry"'),
		('Record "Repr. Rank Evaluation"','Record "ZS Rep. Rank Evaluation"'),
		('Record "Repr. Rank Exception"','Record "ZS Rep. Rank Exception"'),
		('Record "Repr. Rank Exception Entry"','Record "ZS Rep. Rank Exception Entry"'),
		('Record "Representative Structure"','Record "ZS Rep. Structure"'),
		('Record "Representative Structure Entry"','Record "ZS Rep. Structure Entry"'),
		('Record "Representative Structure Print"','Record "ZS Rep. Structure Print"'),
		('Record "Representative Turnover"','Record "ZS Rep. Turnover"'),
		('Record "Representative Turnover Entry"','Record "ZS Rep. Turnover Entry"'),
		('Record "ZS Report Selections"','Record "ZS Report Selections"'),
		('Record "Representative Contract"','Record "ZS Repr. Contract"'),
		('Record "Repr. Contract Comment"','Record "ZS Repr. Contract Comment"'),
		('Record "Representative Contract Type"','Record "ZS Repr. Contract Type"'),
		('Record "Rep. Contract Posting Group"','Record "ZS Repr. Ctr. Posting Group"'),
		('Record "Repr. Contract Sales Program"','Record "ZS Repr. Ctr. Sales Program"'),
		('Record "Detailed Rep. Ledger Entry"','Record "ZS Repr. Detailed Ledger Entry"'),
		('Record "Representative Discount Param"','Record "ZS Repr. Discount Param"'),
		('Record "Representative Exam"','Record "ZS Repr. Exam"'),
		('Record "Rep. Installment Payment Line"','Record "ZS Repr. Installment Pay. Line"'),
		('Record "Rep. Installment Payment"','Record "ZS Repr. Installment Payment"'),
		('Record "Rep. Journal Batch"','Record "ZS Repr. Journal Batch"'),
		('Record "Rep. Journal Line"','Record "ZS Repr. Journal Line"'),
		('Record "Rep. Journal Template"','Record "ZS Repr. Journal Template"'),
		('Record "Rep. Ledger Entry"','Record "ZS Repr. Ledger Entry"'),
		('Record "Representative Level Entry"','Record "ZS Repr. Level Entry"'),
		('Record "Rep. Register"','Record "ZS Repr. Register"'),
		('Record "Sales Program Director"','Record "ZS Repr. Sales Prog. Director"'),
		('Record "Rule Calc. Buffer"','Record "ZS Rule Calc. Buffer"'),
		('Record "Sales Item"','Record "ZS Sales Item"'),
		('Record "Sales Item Commision Rate"','Record "ZS Sales Item Commision Rate"'),
		('Record "Commission Group"','Record "ZS Sales Item Commission Group"'),
		('Record "Sales Item Ext. Feature"','Record "ZS Sales Item Ext. Feature"'),
		('Record "Feature"','Record "ZS Sales Item Feature"'),
		('Record "Item Feature Priority"','Record "ZS Sales Item Feature Priority"'),
		('Record "Gift Category"','Record "ZS Sales Item Gift Category"'),
		('Record "Internal Brand Define"','Record "ZS Sales Item Int. Brand Def."'),
		('Record "Margin Factor Comm. Rate"','Record "ZS Sales Item M.F. Comm. Rate"'),
		('Record "Sales Contract Price"','Record "ZS Sales Item Price"'),
		('Record "Sales Price Group"','Record "ZS Sales Item Price Group"'),
		('Record "Sales Ctr. Price Supp. Turn."','Record "ZS Sales Item Price Sup. Tur."'),
		('Record "Sales Contract Price Wrksh."','Record "ZS Sales Item Price Wrksh."'),
		('Record "Sales Item Spec."','Record "ZS Sales Item Spec."'),
		('Record "Supporting Turnover"','Record "ZS Sales Item Supp. Turnover"'),
		('Record "Item Supplement"','Record "ZS Sales Item Supplement"'),
		('Record "Sales Item Translation"','Record "ZS Sales Item Translation"'),
		('Record "Variant"','Record "ZS Sales Item Variant"'),
		('Record "Sales Program"','Record "ZS Sales Program"'),
		('Record Sample;','Record "ZS Sample";'),
		('Record "Master Case Contract"','Record "ZS Sample Contract"'),
		('Record "Master Case Ctr. Comment Line"','Record "ZS Sample Ctr. Comment Line"'),
		('Record "Master Case Ctr. Event Log"','Record "ZS Sample Ctr. Event Log"'),
		('Record "Master Case Ctr. Turnover"','Record "ZS Sample Ctr. Turnover"'),
		('Record "Sample Journal Batch"','Record "ZS Sample Journal Batch"'),
		('Record "Sample Journal Line"','Record "ZS Sample Journal Line"'),
		('Record "Sample Journal Template"','Record "ZS Sample Journal Template"'),
		('Record "Sample Ledger Entry"','Record "ZS Sample Ledger Entry"'),
		('Record "Next Status"','Record "ZS Sample Next Status"'),
		('Record "Posted Sample Shpt. Header"','Record "ZS Sample Posted Shpt. Header"'),
		('Record "Posted Sample Shpt. Line"','Record "ZS Sample Posted Shpt. Line"'),
		('Record "Sample Register"','Record "ZS Sample Register"'),
		('Record "Sample Shipment Header"','Record "ZS Sample Shipment Header"'),
		('Record "Sample Shipment Line"','Record "ZS Sample Shipment Line"'),
		('Record Status;','Record "ZS Sample Status";'),
		('Record "Status User"','Record "ZS Sample Status User"'),
		('Record "Mast. Case Turnover Setup"','Record "ZS Sample Turnover Setup"'),
		('Record "Master Case Type"','Record "ZS Sample Type"'),
		('Record "Service Employee"','Record "ZS Srv. Employee"'),
		('Record "Service Item Application Entry"','Record "ZS Srv. Item Applicat. Entry"'),
		('Record "Service Item Journal Batch"','Record "ZS Srv. Item Journal Batch"'),
		('Record "Service Item Journal Line"','Record "ZS Srv. Item Journal Line"'),
		('Record "Service Item Journal Template"','Record "ZS Srv. Item Journal Template"'),
		('Record "Service Item Ledger Entry"','Record "ZS Srv. Item Ledger Entry"'),
		('Record "Service Item Register"','Record "ZS Srv. Item Register"'),
		('Record "Serv. Item Shpt. Header"','Record "ZS Srv. Item Shpt. Header"'),
		('Record "Serv. Item Shpt. Line"','Record "ZS Srv. Item Shpt. Line"'),
		('Record "Serv. Item Trans. Rcpt. Header"','Record "ZS Srv. Item Tran. Rcpt. Head."'),
		('Record "Serv. Item Trans. Rcpt. Line"','Record "ZS Srv. Item Tran. Rcpt. Line"'),
		('Record "Serv. Item Trans. Shpt. Header"','Record "ZS Srv. Item Tran. Shp. Header"'),
		('Record "Serv. Item Trans. Shpt. Line"','Record "ZS Srv. Item Tran. Shp. Line"'),
		('Record "Service Item Transfer Header"','Record "ZS Srv. Item Transfer Header"'),
		('Record "Service Item Transfer Line"','Record "ZS Srv. Item Transfer Line"'),
		('Record "Overhaul Order Line Detail"','Record "ZS Srv. Over. Order Line Det."'),
		('Record "Overhaul Order Header"','Record "ZS Srv. Overhaul Order Header"'),
		('Record "Overhaul Order Line"','Record "ZS Srv. Overhaul Order Line"'),
		('Record "Posted Serv. Item Shpt. Header"','Record "ZS Srv. Post. Item Shpt. Head."'),
		('Record "Posted Serv. Item Shpt. Line"','Record "ZS Srv. Post. Item Shpt. Line"'),
		('Record "Posted Overhaul Line Detail"','Record "ZS Srv. Post. Over. Line Det."'),
		('Record "Posted Overhaul Header"','Record "ZS Srv. Posted Overhaul Header"'),
		('Record "Posted Overhaul Line"','Record "ZS Srv. Posted Overhaul Line"'),
		('Record "ZS Vendor Template"','Record "ZS Vendor Template"'),

		('TableData "Zepter Soft Setup"','TableData "Zepter Soft Setup"'),
		('TableData "Zepter Soft User"','TableData "Zepter Soft User"'),
		('TableData "Analysis Overview"','TableData "ZS Analysis Overview"'),
		('TableData Calendar;','TableData "ZS Calendar";'),
		('TableData "Calendar Base Unit"','TableData "ZS Calendar Base Unit"'),
		('TableData "Calendar Detail"','TableData "ZS Calendar Detail"'),
		('TableData "Commission Calculation Code"','TableData "ZS Comm. Calculation Code"'),
		('TableData "Calculation Register"','TableData "ZS Comm. Calculation Register"'),
		('TableData "Commission Calendar"','TableData "ZS Comm. Calendar"'),
		('TableData "Commission Entry Allocation"','TableData "ZS Comm. Entry Allocation"'),
		('TableData "Detailed Comm. Ledg. Entry"','TableData "ZS Comm. Ledger Detailed Entry"'),
		('TableData "Commission Ledger Entry"','TableData "ZS Comm. Ledger Entry"'),
		('TableData "Rep. Commission Par. Exception"','TableData "ZS Comm. Par. Exception"'),
		('TableData "Commission Param by Contract"','TableData "ZS Comm. Param by Contract"'),
		('TableData "Commission Param by Level"','TableData "ZS Comm. Param by Level"'),
		('TableData "Commission Param by Turnover"','TableData "ZS Comm. Param by Turnover"'),
		('TableData "Partner Commission Setup"','TableData "ZS Comm. Partner Setup"'),
		('TableData "Commission Payment Qualifier"','TableData "ZS Comm. Payment Qualifier"'),
		('TableData "Sales Ctr. Initial Commission"','TableData "ZS Comm. Sales Ctr. Initial"'),
		('TableData "Sales Ctr. Commission Rule"','TableData "ZS Comm. Sales Ctr. Rule"'),
		('TableData "Commission Setup"','TableData "ZS Comm. Setup"'),
		('TableData "Commission Worksheet"','TableData "ZS Comm. Worksheet"'),
		('TableData "Imp. Purchase Header"','TableData "ZS Imp. Purchase Header"'),
		('TableData "Imp. Purchase Line"','TableData "ZS Imp. Purchase Line"'),
		('TableData "Ledger Entry Comment Line"','TableData "ZS Ledger Entry Comment Line"'),
		('TableData "Personal Data Proc. Consent"','TableData "ZS Personal Data Proc. Consent"'),
		('TableData "Personal Data Processing Code"','TableData "ZS Personal Data Proces. Code"'),
		('TableData "Personal Data Protection Field"','TableData "ZS Personal Data Protec. Field"'),
		('TableData "Personal Data Request Entry"','TableData "ZS Personal Data Req. Entry"'),
		('TableData "Personal Data Request"','TableData "ZS Personal Data Request"'),
		('TableData "Personal Voucher Ledger Entry"','TableData "ZS Personal Vouch. Ledg. Entry"'),
		('TableData "Personal Voucher"','TableData "ZS Personal Voucher"'),
		('TableData "Voucher Price"','TableData "ZS Personal Voucher Price"'),
		('TableData "Personal Voucher Template"','TableData "ZS Personal Voucher Template"'),
		('TableData "Contract Journal Batch"','TableData "ZS Pmt. Ctr. Journal Batch"'),
		('TableData "Contract Journal Line"','TableData "ZS Pmt. Ctr. Journal Line"'),
		('TableData "Contract Journal Template"','TableData "ZS Pmt. Ctr. Journal Template"'),
		('TableData "Detailed Contract Ledger Entry"','TableData "ZS Pmt. Ctr. Ledg. Det. Entry"'),
		('TableData "Contract Ledger Entry"','TableData "ZS Pmt. Ctr. Ledger Entry"'),
		('TableData "ZS Contract Register"','TableData "ZS Pmt. Ctr. Register"'),
		('TableData "Filter Part Buffer"','TableData "ZS Pmt. Filter Part Buffer"'),
		('TableData "Det. Freezing Ledger Entry"','TableData "ZS Pmt. Freez.Ledg. Det. Entry"'),
		('TableData "Freezing Ledger Entry"','TableData "ZS Pmt. Freez.Ledg. Entry"'),
		('TableData "Pmt. Return Wksh. Batch"','TableData "ZS Pmt. Return Wksh. Batch"'),
		('TableData "Pmt. Return Wksh. Line"','TableData "ZS Pmt. Return Wksh. Line"'),
		('TableData "Pmt. Return Wksh. Template"','TableData "ZS Pmt. Return Wksh. Template"'),
		('TableData "Sales Adv. Corr. Header"','TableData "ZS Pmt. Sales Adv.Corr. Header"'),
		('TableData "Sales Adv. Corr. Line"','TableData "ZS Pmt. Sales Adv.Corr. Line"'),
		('TableData "Advance Application"','TableData "ZS Pmt. Sales Advance Appl."'),
		('TableData "Sales Advance Header"','TableData "ZS Pmt. Sales Advance Header"'),
		('TableData "Sales Advance Line"','TableData "ZS Pmt. Sales Advance Line"'),
		('TableData "Transfer Order"','TableData "ZS Pmt. Transfer Order"'),
		('TableData "Transfer Order Setup"','TableData "ZS Pmt. Transfer Order Setup"'),
		('TableData "Rank & Turnover Addit. Setup"','TableData "ZS Rank & Turn. Addit. Setup"'),
		('TableData "Rank & Turnover Definition"','TableData "ZS Rank & Turnover Definition"'),
		('TableData "Rank & Turnover Setup"','TableData "ZS Rank & Turnover Setup"'),
		('TableData "Representative Active"','TableData "ZS Rep. Active"'),
		('TableData "Representative Active Entry"','TableData "ZS Rep. Active Entry"'),
		('TableData "Detailed Repr. Turn. Entry"','TableData "ZS Rep. Detailed Turn. Entry"'),
		('TableData "Detailed Repr. Turnover"','TableData "ZS Rep. Detailed Turnover"'),
		('TableData "Representative Rank"','TableData "ZS Rep. Rank"'),
		('TableData "Representative Rank Entry"','TableData "ZS Rep. Rank Entry"'),
		('TableData "Repr. Rank Evaluation"','TableData "ZS Rep. Rank Evaluation"'),
		('TableData "Repr. Rank Exception"','TableData "ZS Rep. Rank Exception"'),
		('TableData "Repr. Rank Exception Entry"','TableData "ZS Rep. Rank Exception Entry"'),
		('TableData "Representative Structure"','TableData "ZS Rep. Structure"'),
		('TableData "Representative Structure Entry"','TableData "ZS Rep. Structure Entry"'),
		('TableData "Representative Structure Print"','TableData "ZS Rep. Structure Print"'),
		('TableData "Representative Turnover"','TableData "ZS Rep. Turnover"'),
		('TableData "Representative Turnover Entry"','TableData "ZS Rep. Turnover Entry"'),
		('TableData "ZS Report Selections"','TableData "ZS Report Selections"'),
		('TableData "Representative Contract"','TableData "ZS Repr. Contract"'),
		('TableData "Repr. Contract Comment"','TableData "ZS Repr. Contract Comment"'),
		('TableData "Representative Contract Type"','TableData "ZS Repr. Contract Type"'),
		('TableData "Rep. Contract Posting Group"','TableData "ZS Repr. Ctr. Posting Group"'),
		('TableData "Repr. Contract Sales Program"','TableData "ZS Repr. Ctr. Sales Program"'),
		('TableData "Detailed Rep. Ledger Entry"','TableData "ZS Repr. Detailed Ledger Entry"'),
		('TableData "Representative Discount Param"','TableData "ZS Repr. Discount Param"'),
		('TableData "Representative Exam"','TableData "ZS Repr. Exam"'),
		('TableData "Rep. Installment Payment Line"','TableData "ZS Repr. Installment Pay. Line"'),
		('TableData "Rep. Installment Payment"','TableData "ZS Repr. Installment Payment"'),
		('TableData "Rep. Journal Batch"','TableData "ZS Repr. Journal Batch"'),
		('TableData "Rep. Journal Line"','TableData "ZS Repr. Journal Line"'),
		('TableData "Rep. Journal Template"','TableData "ZS Repr. Journal Template"'),
		('TableData "Rep. Ledger Entry"','TableData "ZS Repr. Ledger Entry"'),
		('TableData "Representative Level Entry"','TableData "ZS Repr. Level Entry"'),
		('TableData "Rep. Register"','TableData "ZS Repr. Register"'),
		('TableData "Sales Program Director"','TableData "ZS Repr. Sales Prog. Director"'),
		('TableData "Rule Calc. Buffer"','TableData "ZS Rule Calc. Buffer"'),
		('TableData "Sales Item"','TableData "ZS Sales Item"'),
		('TableData "Sales Item Commision Rate"','TableData "ZS Sales Item Commision Rate"'),
		('TableData "Commission Group"','TableData "ZS Sales Item Commission Group"'),
		('TableData "Sales Item Ext. Feature"','TableData "ZS Sales Item Ext. Feature"'),
		('TableData "Feature"','TableData "ZS Sales Item Feature"'),
		('TableData "Item Feature Priority"','TableData "ZS Sales Item Feature Priority"'),
		('TableData "Gift Category"','TableData "ZS Sales Item Gift Category"'),
		('TableData "Internal Brand Define"','TableData "ZS Sales Item Int. Brand Def."'),
		('TableData "Margin Factor Comm. Rate"','TableData "ZS Sales Item M.F. Comm. Rate"'),
		('TableData "Sales Contract Price"','TableData "ZS Sales Item Price"'),
		('TableData "Sales Price Group"','TableData "ZS Sales Item Price Group"'),
		('TableData "Sales Ctr. Price Supp. Turn."','TableData "ZS Sales Item Price Sup. Tur."'),
		('TableData "Sales Contract Price Wrksh."','TableData "ZS Sales Item Price Wrksh."'),
		('TableData "Sales Item Spec."','TableData "ZS Sales Item Spec."'),
		('TableData "Supporting Turnover"','TableData "ZS Sales Item Supp. Turnover"'),
		('TableData "Item Supplement"','TableData "ZS Sales Item Supplement"'),
		('TableData "Sales Item Translation"','TableData "ZS Sales Item Translation"'),
		('TableData "Variant"','TableData "ZS Sales Item Variant"'),
		('TableData "Sales Program"','TableData "ZS Sales Program"'),
		('TableData Sample;','TableData "ZS Sample";'),
		('TableData "Master Case Contract"','TableData "ZS Sample Contract"'),
		('TableData "Master Case Ctr. Comment Line"','TableData "ZS Sample Ctr. Comment Line"'),
		('TableData "Master Case Ctr. Event Log"','TableData "ZS Sample Ctr. Event Log"'),
		('TableData "Master Case Ctr. Turnover"','TableData "ZS Sample Ctr. Turnover"'),
		('TableData "Sample Journal Batch"','TableData "ZS Sample Journal Batch"'),
		('TableData "Sample Journal Line"','TableData "ZS Sample Journal Line"'),
		('TableData "Sample Journal Template"','TableData "ZS Sample Journal Template"'),
		('TableData "Sample Ledger Entry"','TableData "ZS Sample Ledger Entry"'),
		('TableData "Next Status"','TableData "ZS Sample Next Status"'),
		('TableData "Posted Sample Shpt. Header"','TableData "ZS Sample Posted Shpt. Header"'),
		('TableData "Posted Sample Shpt. Line"','TableData "ZS Sample Posted Shpt. Line"'),
		('TableData "Sample Register"','TableData "ZS Sample Register"'),
		('TableData "Sample Shipment Header"','TableData "ZS Sample Shipment Header"'),
		('TableData "Sample Shipment Line"','TableData "ZS Sample Shipment Line"'),
		('TableData Status;','TableData "ZS Sample Status";'),
		('TableData "Status User"','TableData "ZS Sample Status User"'),
		('TableData "Mast. Case Turnover Setup"','TableData "ZS Sample Turnover Setup"'),
		('TableData "Master Case Type"','TableData "ZS Sample Type"'),
		('TableData "Service Employee"','TableData "ZS Srv. Employee"'),
		('TableData "Service Item Application Entry"','TableData "ZS Srv. Item Applicat. Entry"'),
		('TableData "Service Item Journal Batch"','TableData "ZS Srv. Item Journal Batch"'),
		('TableData "Service Item Journal Line"','TableData "ZS Srv. Item Journal Line"'),
		('TableData "Service Item Journal Template"','TableData "ZS Srv. Item Journal Template"'),
		('TableData "Service Item Ledger Entry"','TableData "ZS Srv. Item Ledger Entry"'),
		('TableData "Service Item Register"','TableData "ZS Srv. Item Register"'),
		('TableData "Serv. Item Shpt. Header"','TableData "ZS Srv. Item Shpt. Header"'),
		('TableData "Serv. Item Shpt. Line"','TableData "ZS Srv. Item Shpt. Line"'),
		('TableData "Serv. Item Trans. Rcpt. Header"','TableData "ZS Srv. Item Tran. Rcpt. Head."'),
		('TableData "Serv. Item Trans. Rcpt. Line"','TableData "ZS Srv. Item Tran. Rcpt. Line"'),
		('TableData "Serv. Item Trans. Shpt. Header"','TableData "ZS Srv. Item Tran. Shp. Header"'),
		('TableData "Serv. Item Trans. Shpt. Line"','TableData "ZS Srv. Item Tran. Shp. Line"'),
		('TableData "Service Item Transfer Header"','TableData "ZS Srv. Item Transfer Header"'),
		('TableData "Service Item Transfer Line"','TableData "ZS Srv. Item Transfer Line"'),
		('TableData "Overhaul Order Line Detail"','TableData "ZS Srv. Over. Order Line Det."'),
		('TableData "Overhaul Order Header"','TableData "ZS Srv. Overhaul Order Header"'),
		('TableData "Overhaul Order Line"','TableData "ZS Srv. Overhaul Order Line"'),
		('TableData "Posted Serv. Item Shpt. Header"','TableData "ZS Srv. Post. Item Shpt. Head."'),
		('TableData "Posted Serv. Item Shpt. Line"','TableData "ZS Srv. Post. Item Shpt. Line"'),
		('TableData "Posted Overhaul Line Detail"','TableData "ZS Srv. Post. Over. Line Det."'),
		('TableData "Posted Overhaul Header"','TableData "ZS Srv. Posted Overhaul Header"'),
		('TableData "Posted Overhaul Line"','TableData "ZS Srv. Posted Overhaul Line"'),
		('TableData "ZS Vendor Template"','TableData "ZS Vendor Template"'),

		('SourceTable = "Zepter Soft Setup"','SourceTable = "Zepter Soft Setup"'),
		('SourceTable = "Zepter Soft User"','SourceTable = "Zepter Soft User"'),
		('SourceTable = "Analysis Overview"','SourceTable = "ZS Analysis Overview"'),
		('SourceTable = Calendar;','SourceTable = "ZS Calendar";'),
		('SourceTable = "Calendar Base Unit"','SourceTable = "ZS Calendar Base Unit"'),
		('SourceTable = "Calendar Detail"','SourceTable = "ZS Calendar Detail"'),
		('SourceTable = "Commission Calculation Code"','SourceTable = "ZS Comm. Calculation Code"'),
		('SourceTable = "Calculation Register"','SourceTable = "ZS Comm. Calculation Register"'),
		('SourceTable = "Commission Calendar"','SourceTable = "ZS Comm. Calendar"'),
		('SourceTable = "Commission Entry Allocation"','SourceTable = "ZS Comm. Entry Allocation"'),
		('SourceTable = "Detailed Comm. Ledg. Entry"','SourceTable = "ZS Comm. Ledger Detailed Entry"'),
		('SourceTable = "Commission Ledger Entry"','SourceTable = "ZS Comm. Ledger Entry"'),
		('SourceTable = "Rep. Commission Par. Exception"','SourceTable = "ZS Comm. Par. Exception"'),
		('SourceTable = "Commission Param by Contract"','SourceTable = "ZS Comm. Param by Contract"'),
		('SourceTable = "Commission Param by Level"','SourceTable = "ZS Comm. Param by Level"'),
		('SourceTable = "Commission Param by Turnover"','SourceTable = "ZS Comm. Param by Turnover"'),
		('SourceTable = "Partner Commission Setup"','SourceTable = "ZS Comm. Partner Setup"'),
		('SourceTable = "Commission Payment Qualifier"','SourceTable = "ZS Comm. Payment Qualifier"'),
		('SourceTable = "Sales Ctr. Initial Commission"','SourceTable = "ZS Comm. Sales Ctr. Initial"'),
		('SourceTable = "Sales Ctr. Commission Rule"','SourceTable = "ZS Comm. Sales Ctr. Rule"'),
		('SourceTable = "Commission Setup"','SourceTable = "ZS Comm. Setup"'),
		('SourceTable = "Commission Worksheet"','SourceTable = "ZS Comm. Worksheet"'),
		('SourceTable = "Imp. Purchase Header"','SourceTable = "ZS Imp. Purchase Header"'),
		('SourceTable = "Imp. Purchase Line"','SourceTable = "ZS Imp. Purchase Line"'),
		('SourceTable = "Ledger Entry Comment Line"','SourceTable = "ZS Ledger Entry Comment Line"'),
		('SourceTable = "Personal Data Proc. Consent"','SourceTable = "ZS Personal Data Proc. Consent"'),
		('SourceTable = "Personal Data Processing Code"','SourceTable = "ZS Personal Data Proces. Code"'),
		('SourceTable = "Personal Data Protection Field"','SourceTable = "ZS Personal Data Protec. Field"'),
		('SourceTable = "Personal Data Request Entry"','SourceTable = "ZS Personal Data Req. Entry"'),
		('SourceTable = "Personal Data Request"','SourceTable = "ZS Personal Data Request"'),
		('SourceTable = "Personal Voucher Ledger Entry"','SourceTable = "ZS Personal Vouch. Ledg. Entry"'),
		('SourceTable = "Personal Voucher"','SourceTable = "ZS Personal Voucher"'),
		('SourceTable = "Voucher Price"','SourceTable = "ZS Personal Voucher Price"'),
		('SourceTable = "Personal Voucher Template"','SourceTable = "ZS Personal Voucher Template"'),
		('SourceTable = "Contract Journal Batch"','SourceTable = "ZS Pmt. Ctr. Journal Batch"'),
		('SourceTable = "Contract Journal Line"','SourceTable = "ZS Pmt. Ctr. Journal Line"'),
		('SourceTable = "Contract Journal Template"','SourceTable = "ZS Pmt. Ctr. Journal Template"'),
		('SourceTable = "Detailed Contract Ledger Entry"','SourceTable = "ZS Pmt. Ctr. Ledg. Det. Entry"'),
		('SourceTable = "Contract Ledger Entry"','SourceTable = "ZS Pmt. Ctr. Ledger Entry"'),
		('SourceTable = "ZS Contract Register"','SourceTable = "ZS Pmt. Ctr. Register"'),
		('SourceTable = "Filter Part Buffer"','SourceTable = "ZS Pmt. Filter Part Buffer"'),
		('SourceTable = "Det. Freezing Ledger Entry"','SourceTable = "ZS Pmt. Freez.Ledg. Det. Entry"'),
		('SourceTable = "Freezing Ledger Entry"','SourceTable = "ZS Pmt. Freez.Ledg. Entry"'),
		('SourceTable = "Pmt. Return Wksh. Batch"','SourceTable = "ZS Pmt. Return Wksh. Batch"'),
		('SourceTable = "Pmt. Return Wksh. Line"','SourceTable = "ZS Pmt. Return Wksh. Line"'),
		('SourceTable = "Pmt. Return Wksh. Template"','SourceTable = "ZS Pmt. Return Wksh. Template"'),
		('SourceTable = "Sales Adv. Corr. Header"','SourceTable = "ZS Pmt. Sales Adv.Corr. Header"'),
		('SourceTable = "Sales Adv. Corr. Line"','SourceTable = "ZS Pmt. Sales Adv.Corr. Line"'),
		('SourceTable = "Advance Application"','SourceTable = "ZS Pmt. Sales Advance Appl."'),
		('SourceTable = "Sales Advance Header"','SourceTable = "ZS Pmt. Sales Advance Header"'),
		('SourceTable = "Sales Advance Line"','SourceTable = "ZS Pmt. Sales Advance Line"'),
		('SourceTable = "Transfer Order"','SourceTable = "ZS Pmt. Transfer Order"'),
		('SourceTable = "Transfer Order Setup"','SourceTable = "ZS Pmt. Transfer Order Setup"'),
		('SourceTable = "Rank & Turnover Addit. Setup"','SourceTable = "ZS Rank & Turn. Addit. Setup"'),
		('SourceTable = "Rank & Turnover Definition"','SourceTable = "ZS Rank & Turnover Definition"'),
		('SourceTable = "Rank & Turnover Setup"','SourceTable = "ZS Rank & Turnover Setup"'),
		('SourceTable = "Representative Active"','SourceTable = "ZS Rep. Active"'),
		('SourceTable = "Representative Active Entry"','SourceTable = "ZS Rep. Active Entry"'),
		('SourceTable = "Detailed Repr. Turn. Entry"','SourceTable = "ZS Rep. Detailed Turn. Entry"'),
		('SourceTable = "Detailed Repr. Turnover"','SourceTable = "ZS Rep. Detailed Turnover"'),
		('SourceTable = "Representative Rank"','SourceTable = "ZS Rep. Rank"'),
		('SourceTable = "Representative Rank Entry"','SourceTable = "ZS Rep. Rank Entry"'),
		('SourceTable = "Repr. Rank Evaluation"','SourceTable = "ZS Rep. Rank Evaluation"'),
		('SourceTable = "Repr. Rank Exception"','SourceTable = "ZS Rep. Rank Exception"'),
		('SourceTable = "Repr. Rank Exception Entry"','SourceTable = "ZS Rep. Rank Exception Entry"'),
		('SourceTable = "Representative Structure"','SourceTable = "ZS Rep. Structure"'),
		('SourceTable = "Representative Structure Entry"','SourceTable = "ZS Rep. Structure Entry"'),
		('SourceTable = "Representative Structure Print"','SourceTable = "ZS Rep. Structure Print"'),
		('SourceTable = "Representative Turnover"','SourceTable = "ZS Rep. Turnover"'),
		('SourceTable = "Representative Turnover Entry"','SourceTable = "ZS Rep. Turnover Entry"'),
		('SourceTable = "ZS Report Selections"','SourceTable = "ZS Report Selections"'),
		('SourceTable = "Representative Contract"','SourceTable = "ZS Repr. Contract"'),
		('SourceTable = "Repr. Contract Comment"','SourceTable = "ZS Repr. Contract Comment"'),
		('SourceTable = "Representative Contract Type"','SourceTable = "ZS Repr. Contract Type"'),
		('SourceTable = "Rep. Contract Posting Group"','SourceTable = "ZS Repr. Ctr. Posting Group"'),
		('SourceTable = "Repr. Contract Sales Program"','SourceTable = "ZS Repr. Ctr. Sales Program"'),
		('SourceTable = "Detailed Rep. Ledger Entry"','SourceTable = "ZS Repr. Detailed Ledger Entry"'),
		('SourceTable = "Representative Discount Param"','SourceTable = "ZS Repr. Discount Param"'),
		('SourceTable = "Representative Exam"','SourceTable = "ZS Repr. Exam"'),
		('SourceTable = "Rep. Installment Payment Line"','SourceTable = "ZS Repr. Installment Pay. Line"'),
		('SourceTable = "Rep. Installment Payment"','SourceTable = "ZS Repr. Installment Payment"'),
		('SourceTable = "Rep. Journal Batch"','SourceTable = "ZS Repr. Journal Batch"'),
		('SourceTable = "Rep. Journal Line"','SourceTable = "ZS Repr. Journal Line"'),
		('SourceTable = "Rep. Journal Template"','SourceTable = "ZS Repr. Journal Template"'),
		('SourceTable = "Rep. Ledger Entry"','SourceTable = "ZS Repr. Ledger Entry"'),
		('SourceTable = "Representative Level Entry"','SourceTable = "ZS Repr. Level Entry"'),
		('SourceTable = "Rep. Register"','SourceTable = "ZS Repr. Register"'),
		('SourceTable = "Sales Program Director"','SourceTable = "ZS Repr. Sales Prog. Director"'),
		('SourceTable = "Rule Calc. Buffer"','SourceTable = "ZS Rule Calc. Buffer"'),
		('SourceTable = "Sales Item"','SourceTable = "ZS Sales Item"'),
		('SourceTable = "Sales Item Commision Rate"','SourceTable = "ZS Sales Item Commision Rate"'),
		('SourceTable = "Commission Group"','SourceTable = "ZS Sales Item Commission Group"'),
		('SourceTable = "Sales Item Ext. Feature"','SourceTable = "ZS Sales Item Ext. Feature"'),
		('SourceTable = "Feature"','SourceTable = "ZS Sales Item Feature"'),
		('SourceTable = "Item Feature Priority"','SourceTable = "ZS Sales Item Feature Priority"'),
		('SourceTable = "Gift Category"','SourceTable = "ZS Sales Item Gift Category"'),
		('SourceTable = "Internal Brand Define"','SourceTable = "ZS Sales Item Int. Brand Def."'),
		('SourceTable = "Margin Factor Comm. Rate"','SourceTable = "ZS Sales Item M.F. Comm. Rate"'),
		('SourceTable = "Sales Contract Price"','SourceTable = "ZS Sales Item Price"'),
		('SourceTable = "Sales Price Group"','SourceTable = "ZS Sales Item Price Group"'),
		('SourceTable = "Sales Ctr. Price Supp. Turn."','SourceTable = "ZS Sales Item Price Sup. Tur."'),
		('SourceTable = "Sales Contract Price Wrksh."','SourceTable = "ZS Sales Item Price Wrksh."'),
		('SourceTable = "Sales Item Spec."','SourceTable = "ZS Sales Item Spec."'),
		('SourceTable = "Supporting Turnover"','SourceTable = "ZS Sales Item Supp. Turnover"'),
		('SourceTable = "Item Supplement"','SourceTable = "ZS Sales Item Supplement"'),
		('SourceTable = "Sales Item Translation"','SourceTable = "ZS Sales Item Translation"'),
		('SourceTable = "Variant"','SourceTable = "ZS Sales Item Variant"'),
		('SourceTable = "Sales Program"','SourceTable = "ZS Sales Program"'),
		('SourceTable = Sample;','SourceTable = "ZS Sample";'),
		('SourceTable = "Master Case Contract"','SourceTable = "ZS Sample Contract"'),
		('SourceTable = "Master Case Ctr. Comment Line"','SourceTable = "ZS Sample Ctr. Comment Line"'),
		('SourceTable = "Master Case Ctr. Event Log"','SourceTable = "ZS Sample Ctr. Event Log"'),
		('SourceTable = "Master Case Ctr. Turnover"','SourceTable = "ZS Sample Ctr. Turnover"'),
		('SourceTable = "Sample Journal Batch"','SourceTable = "ZS Sample Journal Batch"'),
		('SourceTable = "Sample Journal Line"','SourceTable = "ZS Sample Journal Line"'),
		('SourceTable = "Sample Journal Template"','SourceTable = "ZS Sample Journal Template"'),
		('SourceTable = "Sample Ledger Entry"','SourceTable = "ZS Sample Ledger Entry"'),
		('SourceTable = "Next Status"','SourceTable = "ZS Sample Next Status"'),
		('SourceTable = "Posted Sample Shpt. Header"','SourceTable = "ZS Sample Posted Shpt. Header"'),
		('SourceTable = "Posted Sample Shpt. Line"','SourceTable = "ZS Sample Posted Shpt. Line"'),
		('SourceTable = "Sample Register"','SourceTable = "ZS Sample Register"'),
		('SourceTable = "Sample Shipment Header"','SourceTable = "ZS Sample Shipment Header"'),
		('SourceTable = "Sample Shipment Line"','SourceTable = "ZS Sample Shipment Line"'),
		('SourceTable = Status;','SourceTable = "ZS Sample Status";'),
		('SourceTable = "Status User"','SourceTable = "ZS Sample Status User"'),
		('SourceTable = "Mast. Case Turnover Setup"','SourceTable = "ZS Sample Turnover Setup"'),
		('SourceTable = "Master Case Type"','SourceTable = "ZS Sample Type"'),
		('SourceTable = "Service Employee"','SourceTable = "ZS Srv. Employee"'),
		('SourceTable = "Service Item Application Entry"','SourceTable = "ZS Srv. Item Applicat. Entry"'),
		('SourceTable = "Service Item Journal Batch"','SourceTable = "ZS Srv. Item Journal Batch"'),
		('SourceTable = "Service Item Journal Line"','SourceTable = "ZS Srv. Item Journal Line"'),
		('SourceTable = "Service Item Journal Template"','SourceTable = "ZS Srv. Item Journal Template"'),
		('SourceTable = "Service Item Ledger Entry"','SourceTable = "ZS Srv. Item Ledger Entry"'),
		('SourceTable = "Service Item Register"','SourceTable = "ZS Srv. Item Register"'),
		('SourceTable = "Serv. Item Shpt. Header"','SourceTable = "ZS Srv. Item Shpt. Header"'),
		('SourceTable = "Serv. Item Shpt. Line"','SourceTable = "ZS Srv. Item Shpt. Line"'),
		('SourceTable = "Serv. Item Trans. Rcpt. Header"','SourceTable = "ZS Srv. Item Tran. Rcpt. Head."'),
		('SourceTable = "Serv. Item Trans. Rcpt. Line"','SourceTable = "ZS Srv. Item Tran. Rcpt. Line"'),
		('SourceTable = "Serv. Item Trans. Shpt. Header"','SourceTable = "ZS Srv. Item Tran. Shp. Header"'),
		('SourceTable = "Serv. Item Trans. Shpt. Line"','SourceTable = "ZS Srv. Item Tran. Shp. Line"'),
		('SourceTable = "Service Item Transfer Header"','SourceTable = "ZS Srv. Item Transfer Header"'),
		('SourceTable = "Service Item Transfer Line"','SourceTable = "ZS Srv. Item Transfer Line"'),
		('SourceTable = "Overhaul Order Line Detail"','SourceTable = "ZS Srv. Over. Order Line Det."'),
		('SourceTable = "Overhaul Order Header"','SourceTable = "ZS Srv. Overhaul Order Header"'),
		('SourceTable = "Overhaul Order Line"','SourceTable = "ZS Srv. Overhaul Order Line"'),
		('SourceTable = "Posted Serv. Item Shpt. Header"','SourceTable = "ZS Srv. Post. Item Shpt. Head."'),
		('SourceTable = "Posted Serv. Item Shpt. Line"','SourceTable = "ZS Srv. Post. Item Shpt. Line"'),
		('SourceTable = "Posted Overhaul Line Detail"','SourceTable = "ZS Srv. Post. Over. Line Det."'),
		('SourceTable = "Posted Overhaul Header"','SourceTable = "ZS Srv. Posted Overhaul Header"'),
		('SourceTable = "Posted Overhaul Line"','SourceTable = "ZS Srv. Posted Overhaul Line"'),
		('SourceTable = "ZS Vendor Template"','SourceTable = "ZS Vendor Template"'),

		('DataItemTable="Zepter Soft Setup";','DataItemTable="Zepter Soft Setup";'),
		('DataItemTable="Zepter Soft User";','DataItemTable="Zepter Soft User";'),
		('DataItemTable="Analysis Overview";','DataItemTable="ZS Analysis Overview";'),
		('DataItemTable=Calendar;','DataItemTable="ZS Calendar";'),
		('DataItemTable="Calendar Base Unit";','DataItemTable="ZS Calendar Base Unit";'),
		('DataItemTable="Calendar Detail";','DataItemTable="ZS Calendar Detail";'),
		('DataItemTable="Commission Calculation Code";','DataItemTable="ZS Comm. Calculation Code";'),
		('DataItemTable="Calculation Register";','DataItemTable="ZS Comm. Calculation Register";'),
		('DataItemTable="Commission Calendar";','DataItemTable="ZS Comm. Calendar";'),
		('DataItemTable="Commission Entry Allocation";','DataItemTable="ZS Comm. Entry Allocation";'),
		('DataItemTable="Detailed Comm. Ledg. Entry";','DataItemTable="ZS Comm. Ledger Detailed Entry";'),
		('DataItemTable="Commission Ledger Entry";','DataItemTable="ZS Comm. Ledger Entry";'),
		('DataItemTable="Rep. Commission Par. Exception";','DataItemTable="ZS Comm. Par. Exception";'),
		('DataItemTable="Commission Param by Contract";','DataItemTable="ZS Comm. Param by Contract";'),
		('DataItemTable="Commission Param by Level";','DataItemTable="ZS Comm. Param by Level";'),
		('DataItemTable="Commission Param by Turnover";','DataItemTable="ZS Comm. Param by Turnover";'),
		('DataItemTable="Partner Commission Setup";','DataItemTable="ZS Comm. Partner Setup";'),
		('DataItemTable="Commission Payment Qualifier";','DataItemTable="ZS Comm. Payment Qualifier";'),
		('DataItemTable="Sales Ctr. Initial Commission";','DataItemTable="ZS Comm. Sales Ctr. Initial";'),
		('DataItemTable="Sales Ctr. Commission Rule";','DataItemTable="ZS Comm. Sales Ctr. Rule";'),
		('DataItemTable="Commission Setup";','DataItemTable="ZS Comm. Setup";'),
		('DataItemTable="Commission Worksheet";','DataItemTable="ZS Comm. Worksheet";'),
		('DataItemTable="Imp. Purchase Header";','DataItemTable="ZS Imp. Purchase Header";'),
		('DataItemTable="Imp. Purchase Line";','DataItemTable="ZS Imp. Purchase Line";'),
		('DataItemTable="Ledger Entry Comment Line";','DataItemTable="ZS Ledger Entry Comment Line";'),
		('DataItemTable="Personal Data Proc. Consent";','DataItemTable="ZS Personal Data Proc. Consent";'),
		('DataItemTable="Personal Data Processing Code";','DataItemTable="ZS Personal Data Proces. Code";'),
		('DataItemTable="Personal Data Protection Field";','DataItemTable="ZS Personal Data Protec. Field";'),
		('DataItemTable="Personal Data Request Entry";','DataItemTable="ZS Personal Data Req. Entry";'),
		('DataItemTable="Personal Data Request";','DataItemTable="ZS Personal Data Request";'),
		('DataItemTable="Personal Voucher Ledger Entry";','DataItemTable="ZS Personal Vouch. Ledg. Entry";'),
		('DataItemTable="Personal Voucher";','DataItemTable="ZS Personal Voucher";'),
		('DataItemTable="Voucher Price";','DataItemTable="ZS Personal Voucher Price";'),
		('DataItemTable="Personal Voucher Template";','DataItemTable="ZS Personal Voucher Template";'),
		('DataItemTable="Contract Journal Batch";','DataItemTable="ZS Pmt. Ctr. Journal Batch";'),
		('DataItemTable="Contract Journal Line";','DataItemTable="ZS Pmt. Ctr. Journal Line";'),
		('DataItemTable="Contract Journal Template";','DataItemTable="ZS Pmt. Ctr. Journal Template";'),
		('DataItemTable="Detailed Contract Ledger Entry";','DataItemTable="ZS Pmt. Ctr. Ledg. Det. Entry";'),
		('DataItemTable="Contract Ledger Entry";','DataItemTable="ZS Pmt. Ctr. Ledger Entry";'),
		('DataItemTable="ZS Contract Register";','DataItemTable="ZS Pmt. Ctr. Register";'),
		('DataItemTable="Filter Part Buffer";','DataItemTable="ZS Pmt. Filter Part Buffer";'),
		('DataItemTable="Det. Freezing Ledger Entry";','DataItemTable="ZS Pmt. Freez.Ledg. Det. Entry";'),
		('DataItemTable="Freezing Ledger Entry";','DataItemTable="ZS Pmt. Freez.Ledg. Entry";'),
		('DataItemTable="Pmt. Return Wksh. Batch";','DataItemTable="ZS Pmt. Return Wksh. Batch";'),
		('DataItemTable="Pmt. Return Wksh. Line";','DataItemTable="ZS Pmt. Return Wksh. Line";'),
		('DataItemTable="Pmt. Return Wksh. Template";','DataItemTable="ZS Pmt. Return Wksh. Template";'),
		('DataItemTable="Sales Adv. Corr. Header";','DataItemTable="ZS Pmt. Sales Adv.Corr. Header";'),
		('DataItemTable="Sales Adv. Corr. Line";','DataItemTable="ZS Pmt. Sales Adv.Corr. Line";'),
		('DataItemTable="Advance Application";','DataItemTable="ZS Pmt. Sales Advance Appl.";'),
		('DataItemTable="Sales Advance Header";','DataItemTable="ZS Pmt. Sales Advance Header";'),
		('DataItemTable="Sales Advance Line";','DataItemTable="ZS Pmt. Sales Advance Line";'),
		('DataItemTable="Transfer Order";','DataItemTable="ZS Pmt. Transfer Order";'),
		('DataItemTable="Transfer Order Setup";','DataItemTable="ZS Pmt. Transfer Order Setup";'),
		('DataItemTable="Rank & Turnover Addit. Setup";','DataItemTable="ZS Rank & Turn. Addit. Setup";'),
		('DataItemTable="Rank & Turnover Definition";','DataItemTable="ZS Rank & Turnover Definition";'),
		('DataItemTable="Rank & Turnover Setup";','DataItemTable="ZS Rank & Turnover Setup";'),
		('DataItemTable="Representative Active";','DataItemTable="ZS Rep. Active";'),
		('DataItemTable="Representative Active Entry";','DataItemTable="ZS Rep. Active Entry";'),
		('DataItemTable="Detailed Repr. Turn. Entry";','DataItemTable="ZS Rep. Detailed Turn. Entry";'),
		('DataItemTable="Detailed Repr. Turnover";','DataItemTable="ZS Rep. Detailed Turnover";'),
		('DataItemTable="Representative Rank";','DataItemTable="ZS Rep. Rank";'),
		('DataItemTable="Representative Rank Entry";','DataItemTable="ZS Rep. Rank Entry";'),
		('DataItemTable="Repr. Rank Evaluation";','DataItemTable="ZS Rep. Rank Evaluation";'),
		('DataItemTable="Repr. Rank Exception";','DataItemTable="ZS Rep. Rank Exception";'),
		('DataItemTable="Repr. Rank Exception Entry";','DataItemTable="ZS Rep. Rank Exception Entry";'),
		('DataItemTable="Representative Structure";','DataItemTable="ZS Rep. Structure";'),
		('DataItemTable="Representative Structure Entry";','DataItemTable="ZS Rep. Structure Entry";'),
		('DataItemTable="Representative Structure Print";','DataItemTable="ZS Rep. Structure Print";'),
		('DataItemTable="Representative Turnover";','DataItemTable="ZS Rep. Turnover";'),
		('DataItemTable="Representative Turnover Entry";','DataItemTable="ZS Rep. Turnover Entry";'),
		('DataItemTable="ZS Report Selections";','DataItemTable="ZS Report Selections";'),
		('DataItemTable="Representative Contract";','DataItemTable="ZS Repr. Contract";'),
		('DataItemTable="Repr. Contract Comment";','DataItemTable="ZS Repr. Contract Comment";'),
		('DataItemTable="Representative Contract Type";','DataItemTable="ZS Repr. Contract Type";'),
		('DataItemTable="Rep. Contract Posting Group";','DataItemTable="ZS Repr. Ctr. Posting Group";'),
		('DataItemTable="Repr. Contract Sales Program";','DataItemTable="ZS Repr. Ctr. Sales Program";'),
		('DataItemTable="Detailed Rep. Ledger Entry";','DataItemTable="ZS Repr. Detailed Ledger Entry";'),
		('DataItemTable="Representative Discount Param";','DataItemTable="ZS Repr. Discount Param";'),
		('DataItemTable="Representative Exam";','DataItemTable="ZS Repr. Exam";'),
		('DataItemTable="Rep. Installment Payment Line";','DataItemTable="ZS Repr. Installment Pay. Line";'),
		('DataItemTable="Rep. Installment Payment";','DataItemTable="ZS Repr. Installment Payment";'),
		('DataItemTable="Rep. Journal Batch";','DataItemTable="ZS Repr. Journal Batch";'),
		('DataItemTable="Rep. Journal Line";','DataItemTable="ZS Repr. Journal Line";'),
		('DataItemTable="Rep. Journal Template";','DataItemTable="ZS Repr. Journal Template";'),
		('DataItemTable="Rep. Ledger Entry";','DataItemTable="ZS Repr. Ledger Entry";'),
		('DataItemTable="Representative Level Entry";','DataItemTable="ZS Repr. Level Entry";'),
		('DataItemTable="Rep. Register";','DataItemTable="ZS Repr. Register";'),
		('DataItemTable="Sales Program Director";','DataItemTable="ZS Repr. Sales Prog. Director";'),
		('DataItemTable="Rule Calc. Buffer";','DataItemTable="ZS Rule Calc. Buffer";'),
		('DataItemTable="Sales Item";','DataItemTable="ZS Sales Item";'),
		('DataItemTable="Sales Item Commision Rate";','DataItemTable="ZS Sales Item Commision Rate";'),
		('DataItemTable="Commission Group";','DataItemTable="ZS Sales Item Commission Group";'),
		('DataItemTable="Sales Item Ext. Feature";','DataItemTable="ZS Sales Item Ext. Feature";'),
		('DataItemTable="Feature";','DataItemTable="ZS Sales Item Feature";'),
		('DataItemTable="Item Feature Priority";','DataItemTable="ZS Sales Item Feature Priority";'),
		('DataItemTable="Gift Category";','DataItemTable="ZS Sales Item Gift Category";'),
		('DataItemTable="Internal Brand Define";','DataItemTable="ZS Sales Item Int. Brand Def.";'),
		('DataItemTable="Margin Factor Comm. Rate";','DataItemTable="ZS Sales Item M.F. Comm. Rate";'),
		('DataItemTable="Sales Contract Price";','DataItemTable="ZS Sales Item Price";'),
		('DataItemTable="Sales Price Group";','DataItemTable="ZS Sales Item Price Group";'),
		('DataItemTable="Sales Ctr. Price Supp. Turn.";','DataItemTable="ZS Sales Item Price Sup. Tur.";'),
		('DataItemTable="Sales Contract Price Wrksh.";','DataItemTable="ZS Sales Item Price Wrksh.";'),
		('DataItemTable="Sales Item Spec.";','DataItemTable="ZS Sales Item Spec.";'),
		('DataItemTable="Supporting Turnover";','DataItemTable="ZS Sales Item Supp. Turnover";'),
		('DataItemTable="Item Supplement";','DataItemTable="ZS Sales Item Supplement";'),
		('DataItemTable="Sales Item Translation";','DataItemTable="ZS Sales Item Translation";'),
		('DataItemTable="Variant";','DataItemTable="ZS Sales Item Variant";'),
		('DataItemTable="Sales Program";','DataItemTable="ZS Sales Program";'),
		('DataItemTable=Sample;','DataItemTable="ZS Sample";'),
		('DataItemTable="Master Case Contract";','DataItemTable="ZS Sample Contract";'),
		('DataItemTable="Master Case Ctr. Comment Line";','DataItemTable="ZS Sample Ctr. Comment Line";'),
		('DataItemTable="Master Case Ctr. Event Log";','DataItemTable="ZS Sample Ctr. Event Log";'),
		('DataItemTable="Master Case Ctr. Turnover";','DataItemTable="ZS Sample Ctr. Turnover";'),
		('DataItemTable="Sample Journal Batch";','DataItemTable="ZS Sample Journal Batch";'),
		('DataItemTable="Sample Journal Line";','DataItemTable="ZS Sample Journal Line";'),
		('DataItemTable="Sample Journal Template";','DataItemTable="ZS Sample Journal Template";'),
		('DataItemTable="Sample Ledger Entry";','DataItemTable="ZS Sample Ledger Entry";'),
		('DataItemTable="Next Status";','DataItemTable="ZS Sample Next Status";'),
		('DataItemTable="Posted Sample Shpt. Header";','DataItemTable="ZS Sample Posted Shpt. Header";'),
		('DataItemTable="Posted Sample Shpt. Line";','DataItemTable="ZS Sample Posted Shpt. Line";'),
		('DataItemTable="Sample Register";','DataItemTable="ZS Sample Register";'),
		('DataItemTable="Sample Shipment Header";','DataItemTable="ZS Sample Shipment Header";'),
		('DataItemTable="Sample Shipment Line";','DataItemTable="ZS Sample Shipment Line";'),
		('DataItemTable=Status;','DataItemTable="ZS Sample Status";'),
		('DataItemTable="Status User";','DataItemTable="ZS Sample Status User";'),
		('DataItemTable="Mast. Case Turnover Setup";','DataItemTable="ZS Sample Turnover Setup";'),
		('DataItemTable="Master Case Type";','DataItemTable="ZS Sample Type";'),
		('DataItemTable="Service Employee";','DataItemTable="ZS Srv. Employee";'),
		('DataItemTable="Service Item Application Entry";','DataItemTable="ZS Srv. Item Applicat. Entry";'),
		('DataItemTable="Service Item Journal Batch";','DataItemTable="ZS Srv. Item Journal Batch";'),
		('DataItemTable="Service Item Journal Line";','DataItemTable="ZS Srv. Item Journal Line";'),
		('DataItemTable="Service Item Journal Template";','DataItemTable="ZS Srv. Item Journal Template";'),
		('DataItemTable="Service Item Ledger Entry";','DataItemTable="ZS Srv. Item Ledger Entry";'),
		('DataItemTable="Service Item Register";','DataItemTable="ZS Srv. Item Register";'),
		('DataItemTable="Serv. Item Shpt. Header";','DataItemTable="ZS Srv. Item Shpt. Header";'),
		('DataItemTable="Serv. Item Shpt. Line";','DataItemTable="ZS Srv. Item Shpt. Line";'),
		('DataItemTable="Serv. Item Trans. Rcpt. Header";','DataItemTable="ZS Srv. Item Tran. Rcpt. Head.";'),
		('DataItemTable="Serv. Item Trans. Rcpt. Line";','DataItemTable="ZS Srv. Item Tran. Rcpt. Line";'),
		('DataItemTable="Serv. Item Trans. Shpt. Header";','DataItemTable="ZS Srv. Item Tran. Shp. Header";'),
		('DataItemTable="Serv. Item Trans. Shpt. Line";','DataItemTable="ZS Srv. Item Tran. Shp. Line";'),
		('DataItemTable="Service Item Transfer Header";','DataItemTable="ZS Srv. Item Transfer Header";'),
		('DataItemTable="Service Item Transfer Line";','DataItemTable="ZS Srv. Item Transfer Line";'),
		('DataItemTable="Overhaul Order Line Detail";','DataItemTable="ZS Srv. Over. Order Line Det.";'),
		('DataItemTable="Overhaul Order Header";','DataItemTable="ZS Srv. Overhaul Order Header";'),
		('DataItemTable="Overhaul Order Line";','DataItemTable="ZS Srv. Overhaul Order Line";'),
		('DataItemTable="Posted Serv. Item Shpt. Header";','DataItemTable="ZS Srv. Post. Item Shpt. Head.";'),
		('DataItemTable="Posted Serv. Item Shpt. Line";','DataItemTable="ZS Srv. Post. Item Shpt. Line";'),
		('DataItemTable="Posted Overhaul Line Detail";','DataItemTable="ZS Srv. Post. Over. Line Det.";'),
		('DataItemTable="Posted Overhaul Header";','DataItemTable="ZS Srv. Posted Overhaul Header";'),
		('DataItemTable="Posted Overhaul Line";','DataItemTable="ZS Srv. Posted Overhaul Line";'),
		('DataItemTable="ZS Vendor Template";','DataItemTable="ZS Vendor Template"'),
		
		('Codeunit ZSManagement','Codeunit "ZS Mgt."'),
		('Codeunit TextFileImportMgt','Codeunit "ZS Text File Import Mgt."'),

		('[Scope(''Internal'')]','[Scope(''OnPrem'')]')
		
   return $Tables
}